---
- name: Disable and stop containerd
  systemd:
    name: containerd
    daemon_reload: True
    state: stopped
    enabled: False

- name: Unlock the containerd.io package
  dpkg_selections:
    name: containerd.io
    selection: purge

- name: Uninstall containerd.io
  apt:
    name: containerd.io
    state: absent

- name: Remove previously created files and directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /etc/containerd

- name: Remove docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower}} {{ ansible_distribution_release | lower }} stable"
    state: absent
