---
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    token: "{{ kubeadm.token.value }}"
    apiServerEndpoint: "{{ kubernetes.apiServer.loadBalancer.ip }}:6443"
controlPlane:
  localAPIEndpoint:
    advertiseAddress: "{{ ansible_default_ipv4.address }}"
    bindPort: 6443
nodeRegistration:
  name: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
  criSocket: /var/run/containerd/containerd.sock
