---
networkInterface: ens18
docker:
  version: "5:18.09.5~3-0~ubuntu-bionic"
  socket_path: /var/run/dockershim.sock
kubernetes:
  version: "1.18.3"
  auditPolicy:
    logDir: "/var/log/kubernetes/audit"
    logMaxAge: 2
  apiServer:
    loadBalancer:
      ip: "lb.k8s"
  cni:
    version: "0.7.5"
    paths:
      conf: /etc/cni/net.d
      bin: /opt/cni/bin
  dns:
    type: CoreDNS
    image:
      repo: docker.io/coredns
      tag: "1.6.7"
  network:
    dns:
      domain: "cluster.local"
      serviceIP: "10.32.0.10"
    pods:
      cidr: "10.200.0.0/16"
    services:
      cidr: "10.32.0.0/24"
kubelet:
  version: "1.18.3"
kubeadm:
  version: "1.18.3"
kubectl:
  version: "1.18.3"
calico:
  installationURL: "https://docs.projectcalico.org/manifests/calico.yaml"
  metricsEnabled: true
