---
- name: Download the calico yaml
  get_url:
    url: "{{ calico.installationURL }}"
    dest: /tmp/calico.yaml
    force: yes
  when: kubernetes_is_primary_master == true

- name: Replace the default pod CIDR
  lineinfile:
    path: /tmp/calico.yaml
    regexp: "^(\\s+)value:\\s\"192.168.0.0\\/16\"$"
    line: "              value: \"{{ kubernetes.network.pods.cidr }}\""
  when: kubernetes_is_primary_master == true

- name: Apply the calico specs
  shell: "kubectl apply -f {{ item }}"
  with_items:
  - "/tmp/calico.yaml"
  when: kubernetes_is_primary_master == true

- name: Cleanup the calico install
  file:
    path: /tmp/calico.yaml
    state: absent
  when: kubernetes_is_primary_master == true

- name: Turn the felix prometheus metrics on
  shell: "kubectl set env -n kube-system daemonsets/calico-node FELIX_PROMETHEUSMETRICSENABLED=true"
  when: (calico.metricsEnabled == true) and (kubernetes_is_primary_master == true)

- name: Add an annotation so prometheus can scrape calico
  shell: "kubectl -n kube-system patch daemonset calico-node -p '{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"prometheus.io/scrape\": \"true\",\"prometheus.io/port\": \"9091\"}}}}}'"
  when: (calico.metricsEnabled == true) and (kubernetes_is_primary_master == true)
