---
- name: Apply the calico specs
  shell: "kubectl apply -f {{ calico.installationURL }}"
  when: kubernetes_is_primary_master == true

- name: Turn the felix prometheus metrics on
  shell: "kubectl set env -n kube-system daemonsets/calico-node FELIX_PROMETHEUSMETRICSENABLED=true"
  when: (calico.metricsEnabled == true) and (kubernetes_is_primary_master == true)

- name: Add an annotation so prometheus can scrape calico
  shell: "kubectl -n kube-system patch daemonset calico-node -p '{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"prometheus.io/scrape\": \"true\",\"prometheus.io/port\": \"9091\"}}}}}'"
  when: (calico.metricsEnabled == true) and (kubernetes_is_primary_master == true)
