---
- name: Unlock the kubernetes-cni package
  dpkg_selections:
    name: kubernetes-cni
    selection: purge

- name: Uninstall the kubernetes-cni package
  apt:
    name: kubernetes-cni
    state: absent

- name: Cleanup any unused directories and files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ kubernetes.cni.paths.conf }}"
  - "{{ kubernetes.cni.paths.bin }}"
