---
- name: Add docker apt key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower}}/gpg"
    id: 0EBFCD88

- name: Add docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower}} {{ ansible_distribution_release | lower }} stable"
    update_cache: yes

- name: Install containerd
  apt:
    name: "containerd.io={{ containerd.version }}"
    state: present

- name: Lock the containerd package at its current version
  dpkg_selections:
    name: containerd.io
    selection: hold

- name: Create a directory for the containerd config
  file:
    dest: /etc/containerd
    state: directory

- name: Configure the containerd daemon
  template:
    src: etc/containerd/config.toml
    dest: /etc/containerd/config.toml
  notify:
  - Restart containerd

- name: Enable and start the service
  systemd:
    name: containerd
    daemon_reload: True
    state: started
    enabled: True
