---
# Installation based on: https://github.com/containerd/cri/blob/master/docs/installation.md

- name: Determine whether containerd needs to be installed
  stat:
    path: /usr/local/bin/containerd
  register: containerd_binary

- name: Check containerd version (if it's installed)
  command: "/usr/local/bin/containerd --version"
  register: containerd_version
  when: containerd_binary.stat.exists
  changed_when: False
  failed_when: False

- name: Install prerequisites for containerd
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - libseccomp2

- name: Stop containerd from running (if version is incorrect)
  systemd:
    state: started
    name: containerd
  when: containerd_binary.stat.exists and containerd.version not in containerd_version.stdout

- name: Download containerd tarball
  get_url:
    url: "https://storage.googleapis.com/cri-containerd-release/cri-containerd-{{ containerd.version }}.{{ containerd.os }}-{{ containerd.arch }}.tar.gz"
    dest: /tmp
    force: yes
  when: not containerd_binary.stat.exists or containerd.version not in containerd_version.stdout

- name: Unarchive the containerd tarball
  unarchive:
    remote_src: yes
    src: "/tmp/cri-containerd-{{ containerd.version }}.{{ containerd.os }}-{{ containerd.arch }}.tar.gz"
    dest: /
    extra_opts:
    - --no-overwrite-dir
  when: not containerd_binary.stat.exists or containerd.version not in containerd_version.stdout

- name: Make sure containerd is running
  systemd:
    state: started
    name: containerd
