---
etcd_cluster_endpoints: >-
  {%- set foundIndex = {'index': 0} %}
  {%- for host in (ansible_play_hosts | sort) %}
    {%- if (host == hostvars[inventory_hostname|string()]["ansible_default_ipv4"]["address"]) %}
      {{ foundIndex.update({'index': loop.index}) }}
    {%- endif %}
  {%- endfor %}
  {%- for host in ((ansible_play_hosts | sort)[:foundIndex.index]) %}
  {{ hostvars[host]['ansible_hostname'] }}=https://{{ host }}:2380
  {%- if not loop.last %},{% endif %}
  {%- endfor %}
