---
- name: Install an entry for kubernetes
  copy:
    src: etc/modules-load.d/kubernetes.conf
    dest: /etc/modules-load.d/kubernetes.conf
    owner: root
    group: root
    mode: 0644
  notify: service.systemd-modules-load
