---
- name: Perform a kubeadm reset
  shell: "/usr/bin/kubeadm reset --cri-socket=/var/run/containerd/containerd.sock --force"
  when: kubernetes_is_primary_master == true

- name: Remove the init directory
  file:
    path: /etc/kubernetes/init
    state: absent

- name: Remove the addons directory
  file:
    path: /etc/kubernetes/addons
    state: absent
