---
- name: Determine whether kubectl needs to be installed or not
  stat:
    path: /usr/bin/kubectl
  register: kubectl_binary

- name: Check the kubectl version (if it's installed)
  command: "apt-cache policy kubectl"
  register: kubectl_version
  when: kubectl_binary.stat.exists
  changed_when: False
  failed_when: False

- name: Unlock the kubectl package
  dpkg_selections:
    name: kubectl
    selection: install
  vars:
    search_string: "Installed: {{ kubectl.version }}-00"
  when: kubectl_binary.stat.exists and kubectl_version.stdout is not search(search_string)

- name: Install the kubectl package
  apt:
    name: "kubectl={{ kubectl.version }}-00"
    force: yes
    update_cache: yes
  vars:
    search_string: "Installed: {{ kubectl.version }}-00"
  when: not kubectl_binary.stat.exists or kubectl_version.stdout is not search(search_string)

- name: Lock the kubectl package at its specified version
  dpkg_selections:
    name: kubectl
    selection: hold
