---
- name: Determine whether kubernetes-cni needs to be installed or not
  stat:
    path: /opt/cni/bin
  register: kubernetes_cni_folder

- name: Check the kubernetes-cni version (if it's installed)
  command: "apt-cache policy kubernetes-cni"
  register: kubernetes_cni_version
  when: kubernetes_cni_folder.stat.exists
  changed_when: False
  failed_when: False

- name: Unlock the kubernetes-cni package
  dpkg_selections:
    name: kubernetes-cni
    selection: install
  vars:
    search_string: "Installed: {{ kubernetes.cni.version }}-00"
  when: kubernetes_cni_folder.stat.exists and kubernetes_cni_version.stdout is not search(search_string)

- name: Install the kubernetes-cni package
  apt:
    name: "kubernetes-cni={{ kubernetes.cni.version }}-00"
    force: yes
    update_cache: yes
  vars:
    search_string: "Installed: {{ kubernetes.cni.version }}-00"
  when: not kubernetes_cni_folder.stat.exists or kubernetes_cni_version.stdout is not search(search_string)

- name: Lock the kubernetes-cni package at its specified version
  dpkg_selections:
    name: kubernetes-cni
    selection: hold
