---
- hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
  - name: Install python and python-pip for ansible access
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python python-pip)"
    register: output
    changed_when: output.stdout != ""

- hosts: all
  gather_facts: false
  serial: true
  become: yes
  roles:
  - upgrade-os

- hosts: all
  gather_facts: true
  become: yes
  roles:
  - remove-snap
  - disable-swap
  - enable-ipv4-forwarding
  - enable-masquerading
  - install-common-packages
  - install-containerd
  - add-kubernetes-repo
  - install-kubelet
  - install-kubeadm
  - install-kubernetes-cni

- hosts: masters
  gather_facts: true
  become: yes
  roles:
  - install-kubectl
