---
- hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
  - name: Install python and python-pip for ansible access
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python python-pip)"
    register: output
    changed_when: output.stdout != ""

# - hosts: all
#   serial: true
#   become: yes
#   roles:
#   - upgrade-os

# - hosts: all
#   become: yes
#   roles:
#   - remove-snap
#   - disable-swap
#   - enable-ipv4-forwarding
#   - enable-masquerading
#   - install-common-packages
#   - set-bridge-nf-call-iptables
#   - install-containerd
#   - add-kubernetes-repo
#   - install-kubernetes-cni
#   - install-kubelet
#   - install-kubeadm
#   - setup-kubernetes-modules

- hosts: masters
  become: yes
  roles:
  # - install-kubectl
  - temp-clean-kubeadm-up
  - setup-kubeadm-masters
