---
- hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
  - name: Install python and python-pip for ansible access
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python python-pip)"
    register: output
    changed_when: output.stdout != ""

- hosts: kubernetes_nodes
  become: yes
  roles:
  - uninitialize-kubernetes-nodes
  - uninstall-kubeadm
  - uninstall-kubectl
  - uninstall-kubelet
  - uninstall-kubernetes-cni
  - uninstall-kubernetes-modules
  - uninstall-containerd
  - uninstall-common-packages
  - remove-kubernetes-repo
