---
- name: Ensure the /etc/kubernetes directory exists
  file:
    path: /etc/kubernetes
    state: directory

- name: Generate the first kubeadm config
  template:
    src: etc/kubernetes/kubeadm-config-first.yaml
    dest: /etc/kubernetes/kubeadm-config.yaml
    owner: root
    group: root
  delegate_to: "{{ ansible_play_hosts | first }}"
  run_once: true
  when: (inventory_hostname == (ansible_play_hosts | first))

- name: Generate the other kubeadm configs
  template:
    src: etc/kubernetes/kubeadm-config-others.yaml
    dest: /etc/kubernetes/kubeadm-config.yaml
    owner: root
    group: root
  when: (inventory_hostname != (ansible_play_hosts | first))
